# Generated by Django 4.1.2 on 2022-11-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_IsSuccessfull',
            field=models.BooleanField(default=False),
        ),
    ]
