# Generated by Django 4.1.2 on 2022-11-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0002_project_project_issuccessfull'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_Content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_DateEnd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_GoalFund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_Images',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='Project_RecentFund',
            field=models.IntegerField(default=0),
        ),
    ]
