# Generated by Django 4.1.2 on 2022-11-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0003_project_project_content_project_project_dateend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_ShortDescribe',
            field=models.TextField(default='', max_length=100),
        ),
    ]
