# Generated by Django 4.1.2 on 2022-11-29 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewproject', '0004_project_project_shortdescribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Funded_Money', models.IntegerField(default=0)),
                ('Funded_Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewproject.project')),
                ('Project_Funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
