# Generated by Django 4.1.2 on 2022-11-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0005_fundproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_Price',
            field=models.IntegerField(default=0),
        ),
    ]
