# Generated by Django 4.1.2 on 2022-11-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0006_project_project_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_Content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_DateEnd',
            new_name='DateEnd',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_GoalFund',
            new_name='GoalFund',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_Images',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_IsSuccessfull',
            new_name='IsSuccessfull',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_Owner',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_Price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_RecentFund',
            new_name='RecentFund',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_ShortDescribe',
            new_name='ShortDescribe',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_Title',
            new_name='Title',
        ),
    ]
