# Generated by Django 4.1.2 on 2022-11-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0007_rename_project_content_project_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
