# Generated by Django 4.1.2 on 2022-12-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0009_rename_images_project_image_project_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundproject',
            name='Funded_Project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viewproject.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=models.ImageField(null=True, upload_to='project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Image_Content',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
