# Generated by Django 4.1.2 on 2022-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0010_alter_fundproject_funded_project_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=models.ImageField(null=True, upload_to='media/project'),
        ),
    ]
