# Generated by Django 4.1.2 on 2022-12-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0013_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Category',
            field=models.CharField(choices=[('CN', 'Công nghệ'), ('DV', 'Dịch vụ'), ('DL', 'Du lịch'), ('NN', 'Nông nghiệp'), ('GD', 'Giáo dục')], default='', max_length=2),
        ),
    ]
