# Generated by Django 4.1.2 on 2022-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0014_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Category',
            field=models.CharField(choices=[('CN', 'Công nghệ'), ('Dịch Vụ', 'Dịch vụ'), ('DL', 'Du lịch'), ('NN', 'Nông nghiệp'), ('GD', 'Giáo dục')], default='', max_length=20),
        ),
    ]
