# Generated by Django 4.1.2 on 2022-12-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0015_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Content',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='ShortDescribe',
            field=models.TextField(default='', max_length=70),
        ),
    ]
