# Generated by Django 4.1.3 on 2022-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0016_alter_project_content_alter_project_shortdescribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Image_Content',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ShortDescribe',
            field=models.CharField(default='', max_length=400),
        ),
    ]
