# Generated by Django 4.1.2 on 2022-12-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0018_remove_project_issuccessfull_project_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Content',
            field=models.TextField(default=''),
        ),
    ]
