# Generated by Django 4.1.2 on 2022-12-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0019_alter_project_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ShortDescribe',
            field=models.TextField(default='', max_length=80),
        ),
    ]
