# Generated by Django 4.1.2 on 2022-12-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0020_alter_project_shortdescribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Content',
            new_name='Content1',
        ),
        migrations.AddField(
            model_name='project',
            name='Content2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='Content3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='Content4',
            field=models.TextField(default=''),
        ),
    ]
