# Generated by Django 4.1.2 on 2022-12-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewproject', '0023_alter_project_content2_alter_project_content3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Content2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Content3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Content4',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
