# Generated by Django 4.1.2 on 2022-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='User_Phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
