# Generated by Django 4.1.2 on 2022-11-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_money_user_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
