# Generated by Django 4.1.2 on 2022-11-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
