# Generated by Django 4.1.2 on 2022-11-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Image',
            field=models.ImageField(default='/static/images/default_avatar', upload_to=''),
        ),
    ]
