# Generated by Django 4.1.2 on 2022-11-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Image',
            field=models.ImageField(default='/static/images/default_avatar.jpg', upload_to=''),
        ),
    ]
