# Generated by Django 4.1.2 on 2022-11-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='News_Content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='News_Image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
