# Generated by Django 4.1.2 on 2022-12-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_content_news_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='News_Content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='News_Image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='News_Title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='news',
            name='ShortContent',
            field=models.TextField(default=''),
        ),
    ]
