# Generated by Django 4.1.2 on 2022-12-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_news_content_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Title',
            field=models.CharField(max_length=130),
        ),
    ]
